name = "resume-generation-api"
main = "src/index.ts"
compatibility_date = "2026-04-28"
compatibility_flags = ["nodejs_compat"]
routes = [
  { pattern = "jeasonloop.online/api/*", zone_name = "jeasonloop.online" },
  { pattern = "www.jeasonloop.online/api/*", zone_name = "jeasonloop.online" },
]

[[d1_databases]]
binding = "DB"
database_name = "resume_generation"
database_id = "a7d782b0-f812-435a-8146-f009ade9faab"

[vars]
NODE_ENV = "production"
ALLOWED_ORIGINS = "http://jeasonloop.online,https://jeasonloop.online,http://www.jeasonloop.online,https://www.jeasonloop.online,http://resumegen.jeasonloop.online,https://resumegen.jeasonloop.online,http://49.235.169.225,https://resume-generation.pages.dev,https://resume-generation-web.pages.dev"
